import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { AppConfig } from "@/lib/types";

function generateReadme(config: AppConfig): string {
  return `# ${config.name}

${config.description || "Generated with AI App Generator"}

## Entities

${config.entities.map((e) => `### ${e.name}\n${e.fields.map((f) => `- **${f.label || f.name}** (${f.type}${f.required ? ", required" : ""})`).join("\n")}`).join("\n\n")}

## Pages

${config.pages.map((p) => `- **${p.name}** — ${p.type} view for ${p.entity}`).join("\n")}

## Config

\`\`\`json
${JSON.stringify(config, null, 2)}
\`\`\`

Generated by [AI App Generator](https://github.com)
`;
}

function generateSchemaSQL(config: AppConfig): string {
  return config.entities.map((entity) => {
    const cols = entity.fields.map((f) => {
      const sqlType = f.type === "number" ? "NUMERIC" : f.type === "boolean" ? "BOOLEAN" : f.type === "date" ? "TIMESTAMP" : "TEXT";
      return `  ${f.name} ${sqlType}${f.required ? " NOT NULL" : ""}`;
    });
    return `CREATE TABLE ${entity.name.toLowerCase()}s (\n  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,\n${cols.join(",\n")},\n  created_at TIMESTAMP DEFAULT NOW(),\n  updated_at TIMESTAMP DEFAULT NOW()\n);`;
  }).join("\n\n");
}

export async function POST(req: NextRequest, { params }: { params: Promise<{ appId: string }> }) {
  const session = await auth();
  if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { appId } = await params;
  const app = await prisma.app.findFirst({ where: { id: appId, userId: session.user.id } });
  if (!app) return NextResponse.json({ error: "App not found" }, { status: 404 });

  const { githubToken, repoName } = await req.json();
  if (!githubToken || !repoName) return NextResponse.json({ error: "GitHub token and repo name required" }, { status: 400 });

  const config = app.config as AppConfig;

  try {
    // Create repo
    const createRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: { Authorization: `token ${githubToken}`, "Content-Type": "application/json" },
      body: JSON.stringify({ name: repoName, description: config.description || config.name, private: false, auto_init: false }),
    });

    if (!createRes.ok) {
      const err = await createRes.json();
      return NextResponse.json({ error: err.message || "Failed to create repo" }, { status: 400 });
    }

    const repo = await createRes.json();
    const owner = repo.owner.login;

    const files = [
      { path: "README.md", content: generateReadme(config) },
      { path: "schema.sql", content: generateSchemaSQL(config) },
      { path: "app-config.json", content: JSON.stringify(config, null, 2) },
    ];

    for (const file of files) {
      await fetch(`https://api.github.com/repos/${owner}/${repoName}/contents/${file.path}`, {
        method: "PUT",
        headers: { Authorization: `token ${githubToken}`, "Content-Type": "application/json" },
        body: JSON.stringify({ message: `Add ${file.path}`, content: Buffer.from(file.content).toString("base64") }),
      });
    }

    return NextResponse.json({ repoUrl: repo.html_url });
  } catch (err) {
    console.error("GitHub export error:", err);
    return NextResponse.json({ error: "GitHub export failed" }, { status: 500 });
  }
}
